name: Pull Request CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '22.x'

      - name: Install Packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
