name: CI

on:
  push:
    branches: [main, staging]
  pull_request:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: ["22.x"] # extend to other LTS if you like
    env:
      # skip env validation for nextjs since we are just testing
      SKIP_ENV_VALIDATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint & Format check
        run: |
          pnpm prettier --check .
          pnpm check

      - name: Run tests & coverage
        run: pnpm test --coverage

      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@7bf7d3c1b17a0e27c7e0d14190fb39168584bed2

      - name: Build
        if: success()
        run: pnpm build
        env:
          STANDALONE_IN_PROD: true # generate standalone build
