name: Build Docker Image

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # NOTE: No need to use actions/checkout, see:
      # https://github.com/docker/build-push-action/tree/471d1dc4e07e5cdedd4c2171150001c434f0b7a4/?tab=readme-ov-file#git-context

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          push: false
          tags: safedep/platform.safedep.io:latest
